### ISSUE TITLE
Toolbar 2000 really old, FClients missing ?

### ISSUE THREAD

**Issue by SkybuckFlying** [pyscripter/ChatLLM#1]
[dcc32 Error] TB2ExtItems.pas(241): E2003 Undeclared identifier: 'FClients'
[dcc32 Error] TB2ExtItems.pas(254): E2003 Undeclared identifier: 'FClients'
[dcc32 Error] TB2ExtItems.pas(267): E2003 Undeclared identifier: 'FClients'
[dcc32 Error] TB2ExtItems.pas(284): E2003 Undeclared identifier: 'FClients'
[dcc32 Error] TB2ExtItems.pas(297): E2003 Undeclared identifier: 'FClients'
[dcc32 Fatal Error] tb2k_d12.dpk(49): F2063 Could not compile used unit 'TB2ExtItems.pas'

Any idea how to fix this ? Maybe spLib fixes it ?

Akward.

**Comment by pyscripter** [comment]
No it is not.  Install https://github.com/SilverpointDev/sptbxlib,

**Comment by SkybuckFlying** [comment]
I don't like that I have to run a patch exe... plus the code seems old.

I want to run this on RAD Studio 12.2

**Comment by pyscripter** [comment]
The code is not old at all.  Look at the commits and installation instructions.  Using the Multiinstaller is an one click operation.  It runs fine on Delphi 12.2.  It is still the best menu and UI component suite around.  In any case it should be easy to replace it with standard menus.
