### ISSUE TITLE
Code to old for RAD Studio 12.2 ?

### ISSUE THREAD

**Issue by SkybuckFlying** [pyscripter/ChatLLM#2]
I tried installing this in RAD Studio 12.2.

I tried toolbar 2000 original and a modified version of it on github "tbx" ready.
I tried sp tb x lib original and a modified version of it on github.

Original has FClients missing.

The others don't have a project group and seem to use old design time packages and intf etc.

For now I conclude this software cannot work on latest RAD Studio 12.2 or is too difficult to setup.

I did try your LLMSupport isolated into a simple vcl form app without requiring these components.

But could not get it too connect properly... some http protocol issues ?

Would appreciate a simpler app without these old unnecessary toolbar components and sync edit.

A basical VCL forms app should be sufficient demo.

**Comment by pyscripter** [comment]
Duplicate of #1
